export const MESSAGE = {
  LOGIN_SUCCESS: "Login successful",
  USER_REGISTERED: "User registration successful",
  VERIFY_NUMBER: "Please verify your phone number to continue",
  FIELDS_REQUIRED: "All fields are required",
  USER_EXISTS: "User already exists",
  EMAIL_NOT_FOUND: "Email does not exist",
  INVALID_PASSWORD: "Invalid password",
  INVALID_NUMBER: "Phone number should be of 10 digits",
  INVALID_OTP: "Invalid OTP",
  OTP_SENT: "OTP sent successfully",
  INVALID_OTP: "Invalid OTP",
  ENTER_OTP: "Please Enter a 6 digit OTP",
  PHONE_VERIFICATION: "Number verification successful",
  SOMETHING_WRONG: "Something went wrong!",
  USER_PROFILE: "User profile data",
  USER_NOT_FOUND: "User not found",
  PHONE_EXISTS: "Number already in use",
  LOGIN_ERROR: "Invalid email or password",
  SYMBOL_EMPTY: "Symbol could not be empty",
  SYMBOL_ADDED: "Symbol added successfully",
  SYMBOL_ALREADY_EXISTS: "Symbol already exists",
  WATCH_LIST_DATA: "Watch list data",
  SYMBOL_REMOVED: "Symbol removed successfully",
  SYMBOL_NOT_FOUND: "Symbol not found",
};
